# Use the official Python image as a base image
FROM python:3.10.12

# Set the working directory in the container
WORKDIR /authentication_service

# Set the PYTHONPATH environment variable
ENV PYTHONPATH=/authentication_service/src

# Copy the requirements file into the container
COPY src/requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire src directory into the container
COPY src/ ./src/

# Expose port 8000 for the FastAPI application
EXPOSE 8000

ENTRYPOINT [ "python", "src/app.py" ]


FelinAuthLoadBalancer-553989945.eu-north-1.elb.amazonaws.com

curl -X GET "http://FelinAuthLoadBalancer-553989945.eu-north-1.elb.amazonaws.com/verify-merchant?access_token=eyJraWQiOiJrYVk1ZTAxTW1cL3UyOXhqZ24zYUEyUVwvMGhDVnJ4SlwvckhqYnlodlExOWdvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIyMDRjMTkzYy0zMGUxLTcwMWMtOGNiOS0zYzNiMzUzYTc0MmIiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtbm9ydGgtMS5hbWF6b25hd3MuY29tXC9ldS1ub3J0aC0xX1RnV3VuZzBHeCIsInZlcnNpb24iOjIsImNsaWVudF9pZCI6IjRrbG5hYTZqOTU2Z3Qyc2V0ZDY3MGF0ZWVvIiwib3JpZ2luX2p0aSI6ImFlNDA0M2ZlLWYwYTktNGMyMy04ZmRhLWU5YTA2ZDcxMTA5NyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE3MzA4MDEyMzksImV4cCI6MTczMDgwNDgzOSwiaWF0IjoxNzMwODAxMjM5LCJqdGkiOiJiNTQ0ZWU5ZS0zZjljLTRlZWEtYjZlZi0xMGEzZDE1YjI2ZjEiLCJ1c2VybmFtZSI6Imdvb2dsZV8xMDI0MDk1NTI4NDc3OTEzNjg3MzEifQ.B_ohdBeYo6mTQ4MedrJYaVc5ydtBt7CXxXtpe-6e6kUqT1psI6jCE8HnjNq58ru7jEX9rm-gItu7m-i0VkdqVQNXhyhuNS_NJgW9l7HSRyAQK0weMaISYA9yPbhPuqZyDSG-CptLVzlYJaY9dkl7cfspGRyU8RNhCpnbeFu4wiCfbOTPIn3q-WkNCK0bcLiRkRsE6GhmkzvnqT6VfBUY0sqZBxfA8PeMi0TkGMF5fZoK3aIxSufGQh9Htuw6NpliVA31t3WnuMyoUCVDvYvU9pVHhaXUBbCEQmvzI78j7fFZoR9vxLxoAs_wMr_roCOX1WsRrt7S61F-a0uLCVq6Cg"